### ISSUE TITLE
Admin station burns card that cannot be read by the admin station

### ISSUE THREAD

**Issue by jschrempp** [makernexus/RFID_System#29]
To see this, burn an RFID card with the Admin station. Then call the Card Info function. The admin station fails with "unknown card type". But yet the card will work with a check in station.   I note that clientByMemberNumber does not have the ENDOFEVENT marker that was added to clientByClientID to fix bug #25

**Comment by BobGlicksman** [comment]
I also not that clientByMemberNumber is working OK -- the current data shows up on the Admin app.  The Admin station uses clientByClientID for CardInfo (to test the newly burned card).  clientByClientID works for a checkin station but not for the admin station, so their must be something missing from a function call in the latter that was included properly in the former.

**Comment by jschrempp** [comment]
Found that this had to do with the presentation orientation of the card to be burned. It was possible to position the card in a way that the admin station reported it had burned the card, but in fact it had not.
