### ISSUE TITLE
Amilia boxes request a token every minute

### ISSUE THREAD

**Issue by jschrempp** [makernexus/RFID_System#48]
Each box is requesting  a new token each minute. This causes a lot of data operations in the Particle cloud. In just 8 days we did 70,000 DOs; our monthly free limit is 100k.

**Comment by BobGlicksman** [comment]
Typo in webhook was causing the problem.  Corrected and verified that the bug is fixed.

**Comment by BobGlicksman** [comment]
Bug fixed.
